import { Food } from "../class/food";


export const FOODS:Food[]=[{
    id: 501,
    name: 'Joallad Rotti',
    price: 50,
    tax: 0,
    restaurantId: 5004,
    category: ['Biryani', 'South Indian'],
    availability: true,
    imageUrl: 'assets\food\veg\veg\roti.jpeg',
    averageRating: 4.5,
    description: '1 leg piece,1 tikka piece with rice',
    cuisine: 'South Indian',
    type: 'Veg',
},
{
id: 502,
name: 'Holige',
price: 50,
tax: 0,
restaurantId: 5004,
category: ['Snacks', 'Veg', 'Desserts'],
availability: true,
imageUrl: 'assets\food\veg\holige.jpeg',
averageRating: 5,
description: 'Bhadam holige with ghee',
cuisine: 'Desserts',
type: 'Veg',
},
{
id: 503,
name: 'Chapati curry',
price: 50,
tax: 0,
restaurantId: 5004,
category: ['Non-Veg', 'North Indian'],
availability: true,
imageUrl: 'assets\food\veg/chapati.jpeg',
averageRating: 4.5,
description: 'Two chapati and twa types of curry',
cuisine: 'North Indian',
type: 'Veg'
},
{
id: 504,
name: 'Dhosa',
price: 35,
tax: 0,
restaurantId: 5004,
category: ['veg', 'South Indian'],
availability: true,
imageUrl: 'assets\food\veg\dhosa.jpeg',
averageRating: 4.5,
description: 'Crispy dhosa with coconut chitney',
cuisine: 'South Indian',
type: 'Veg'
},
{
id: 505,
name: 'Idli vada',
price: 40,
tax: 10,
restaurantId: 5004,
category: ['Breakfast', 'South Indian'],
availability: true,
imageUrl: 'assets\food\veg\idli.jpeg',
averageRating: 4.5,
description: '1 bowl of noodles ',
cuisine: 'South Indian',
type: 'Veg'
},
//restaurant id = 5002
{
    id: 501,
    name: 'Masala Dosa',
    price: 50,
    tax: 0,
    restaurantId: 5002,
    category: ['Breakfast','South Indian'],
    availability: true,
    imageUrl: 'assets\food\veg\veg\roti.jpeg',
    averageRating: 4.5,
    description: '1 leg piece,1 tikka piece with rice',
    cuisine: 'South Indian',
    type: 'Veg',
},
{
id: 502,
name: 'Papad Masala',
price: 50,
tax: 0,
restaurantId: 5002,
category: ['Snacks', 'Veg', 'Starters'],
availability: true,
imageUrl: 'assets\food\veg\holige.jpeg',
averageRating: 5,
description: 'Bhadam holige with ghee',
cuisine: 'Starters',
type: 'Veg',
},
{
id: 503,
name: 'Kesari Bath',
price: 50,
tax: 0,
restaurantId: 5002,
category: ['Snacks', 'Veg', 'Desserts'],
availability: true,
imageUrl: 'assets\food\veg/chapati.jpeg',
averageRating: 4.5,
description: 'Two chapati and twa types of curry',
cuisine: 'Desserts',
type: 'Veg'
},
{
id: 504,
name: 'Ice-cream',
price: 35,
tax: 0,
restaurantId: 5002,
category: ['veg', 'Desserts'],
availability: true,
imageUrl: 'assets\food\veg\dhosa.jpeg',
averageRating: 4.5,
description: 'Crispy dhosa with coconut chitney',
cuisine: 'Desserts',
type: 'Veg'
},
{
id: 505,
name: 'Meals',
price: 40,
tax: 10,
restaurantId: 5002,
category: ['Meals', 'South Indian'],
availability: true,
imageUrl: 'assets\food\veg\idli.jpeg',
averageRating: 4.5,
description: '1 bowl of noodles ',
cuisine: 'South Indian',
type: 'Veg'
},
//restaurant id="1001" 
{
    id: 501,
    name: 'Neer Dosa',
    price: 50,
    tax: 0,
    restaurantId: 1001,
    category: ['Breakfast', 'South Indian'],
    availability: true,
    imageUrl: 'assets\food\veg\veg\roti.jpeg',
    averageRating: 4.5,
    description: '1 leg piece,1 tikka piece with rice',
    cuisine: 'South Indian',
    type: 'Veg',
},
{
id:502,
name: 'Rice sambar',
price: 50,
tax: 0,
restaurantId: 1001,
category: ['Snacks', 'Veg', 'South Indian'],
availability: true,
imageUrl: 'assets\food\veg\holige.jpeg',
averageRating: 5,
description: 'Bhadam holige with ghee',
cuisine: 'South Indian',
type: 'Veg',
},
{
id:503,
name: 'Puliyogare',
price: 50,
tax: 0,
restaurantId: 1001,
category: ['Snacks', 'Veg', 'South Indian'],
availability: true,
imageUrl: 'assets\food\veg/chapati.jpeg',
averageRating: 4.5,
description: 'Two chapati and twa types of curry',
cuisine: 'South Indian',
type: 'Veg'
},
{
id: 504,
name: 'Ice-cream',
price: 35,
tax: 0,
restaurantId: 1001,
category: ['veg', 'Desserts'],
availability: true,
imageUrl: 'assets\food\veg\dhosa.jpeg',
averageRating: 4.5,
description: 'Crispy dhosa with coconut chitney',
cuisine: 'Desserts',
type:'Veg'
},
{
id: 505,
name: 'payasam',
price: 40,
tax: 10,
restaurantId: 1001,
category: ['Meals', 'Desserts'],
availability: true,
imageUrl: 'assets\food\veg\idli.jpeg',
averageRating: 4.5,
description: '1 bowl of noodles',
cuisine: 'Desserts' ,
type: 'Veg'
},

//restaurant id=5003
{
    id: 501,
    name: 'Chicken biryani',
    price: 50,
    tax: 0,
    restaurantId: 5003,
    category: ['lunch', 'Biryani'],
    availability: true,
    imageUrl: 'assets\food\veg\veg\roti.jpeg',
    averageRating: 4.5,
    description: '1 leg piece,1 tikka piece with rice',
    cuisine: 'Biryani',
    type: 'Veg',
},
{
id: 502,
name: 'Fish',
price: 50,
tax: 0,
restaurantId: 5003,
category: ['Non-Veg', 'South Indian'],
availability: true,
imageUrl: 'assets\food\veg\holige.jpeg',
averageRating: 5,
description: 'Bhadam holige with ghee',
cuisine: 'South Indian',
type: 'Veg',
},
{
id: 503,
name: 'Chicken Tikka',
price: 50,
tax: 0,
restaurantId: 5003,
category: ['Snacks', 'Veg', 'Starters'],
availability: true,
imageUrl: 'assets\food\veg/chapati.jpeg',
averageRating: 4.5,
description: 'Two chapati and twa types of curry',
cuisine: 'Starters',
type: 'Veg'
},
{
id: 504,
name: 'Ice-cream',
price: 35,
tax: 0,
restaurantId: 5003,
category: ['veg', 'Desserts'],
availability: true,
imageUrl: 'assets\food\veg\dhosa.jpeg',
averageRating: 4.5,
description: 'Crispy dhosa with coconut chitney',
cuisine: 'Desserts',
type: 'Veg'
},
{
id: 505,
name: 'Fried Rice',
price: 40,
tax: 10,
restaurantId: 5003,
category: ['Veg', 'North Indian'],
availability: true,
imageUrl: 'assets\food\veg\idli.jpeg',
averageRating: 4.5,
description: '1 bowl of noodles',
cuisine: 'North Indian',
type: 'Veg'
},
//restaurant id=5005
{
    id: 501,
    name: 'Hot Pie',
    price: 50,
    tax: 0,
    restaurantId: 5005,
    category: ['lunch', 'North Indian'],
    availability: true,
    imageUrl: 'assets\food\veg\veg\roti.jpeg',
    averageRating: 4.5,
    description: '1 leg piece,1 tikka piece with rice',
    cuisine: 'North Indian',
    type: 'Veg',
},
{
id: 502,
name: 'Cake',
price: 50,
tax: 0,
restaurantId: 5005,
category: ['Veg', 'Desserts'],
availability: true,
imageUrl: 'assets\food\veg\holige.jpeg',
averageRating: 5,
description: 'Bhadam holige with ghee',
cuisine: 'Desserts',
type: 'Veg',
},
{
id: 503,
name: 'Milkshake',
price: 50,
tax: 0,
restaurantId: 5005,
category: ['Snacks', 'Veg', 'Starters'],
availability: true,
imageUrl: 'assets\food\veg/chapati.jpeg',
averageRating: 4.5,
description: 'Two chapati and twa types of curry',
cuisine: 'Starters',
type: 'Veg'
},
{
id: 504,
name: 'Ice-cream',
price: 35,
tax: 0,
restaurantId: 5005,
category: ['veg', 'Desserts'],
availability: true,
imageUrl: 'assets\food\veg\dhosa.jpeg',
averageRating: 4.5,
description: 'Crispy dhosa with coconut chitney',
cuisine: 'Desserts',
type: 'Veg'
},
{
id: 505,
name: "Gadbad",
price: 40,
tax: 10,
restaurantId: 5005,
category: ['Veg', 'Desserts'],
availability: true,
imageUrl: 'assets\food\veg\idli.jpeg',
averageRating: 4.5,
description: '1 bowl of noodles',
cuisine: 'Desserts',
type: 'Veg'
},
//restaurant id=5006
{
    id: 501,
    name: 'Vegetable Kurma',
    price: 50,
    tax: 0,
    restaurantId: 5006,
    category: ['lunch', 'North Indian'],
    availability: true,
    imageUrl: 'assets\food\veg\veg\roti.jpeg',
    averageRating: 4.5,
    description: '1 leg piece,1 tikka piece with rice',
    cuisine: 'North Indian',
    type: 'Veg',
},
{
id: 502,
name: 'Jeera Rice',
price: 50,
tax: 0,
restaurantId: 5006,
category: ['Veg', 'North Indian'],
availability: true,
imageUrl: 'assets\food\veg\holige.jpeg',
averageRating: 5,
description: 'Bhadam holige with ghee',
cuisine: 'North Indian',
type: 'Veg',
},
{
id: 503,
name: 'Dal Makhani',
price: 50,
tax: 0,
restaurantId: 5006,
category: ['Veg', 'North Indian'],
availability: true,
imageUrl: 'assets\food\veg/chapati.jpeg',
averageRating: 4.5,
description: 'Two chapati and twa types of curry',
cuisine: 'North Indian',
type: 'Veg'
},
{
id: 504,
name: 'Soup',
price: 35,
tax: 0,
restaurantId: 5006,
category: ['veg', 'Starters'],
availability: true,
imageUrl: 'assets\food\veg\dhosa.jpeg',
averageRating: 4.5,
description: 'Crispy dhosa with coconut chitney',
cuisine: 'Starters',
type: 'Veg'
},
{
id: 505,
name: 'Chapathi',
price: 40,
tax: 10,
restaurantId: 5006,
category: ['Veg', 'South Indian'],
availability: true,
imageUrl: 'assets\food\veg\idli.jpeg',
averageRating: 4.5,
description: '1 bowl of noodles',
cuisine: 'South Indian',
type: 'Veg'
}
]