import { Food } from "src/app/class/food";

export const FOODS:Food[]=[
{
    id: 501,
    name: "Joallad Rotti",
    price: 50,
    tax: 3,
    restaurantId: 5001,
    category: "Lunch",
    availability: true,
    imageUrl: "assets\food\veg\veg\roti.jpeg",
    averageRating: 4.5,
    description: "1 leg piece,1 tikka piece with rice",
    cuisine: "SouthIndian",
    type:"Veg",
},
{
    id:502,
    name: "Holige",
    price: 50,
    tax: 5,
    restaurantId: 5001,
    category: "Sweets",
    availability: true,
    imageUrl: "assets\food\veg\holige.jpeg",
    averageRating: 5,
    description: "Bhadam holige with ghee",
    cuisine: "southIndian",
    type:"Veg",
},
{
    id:503,
    name: "Chapati curry",
    price: 50,
    tax: 4,
    restaurantId: 5001,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg/chapati.jpeg",
    averageRating: 4.5,
    description: "Two chapati and twa types of curry",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:504,
    name: "Dhosa",
    price: 35,
    tax: 2,
    restaurantId: 5001,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\dhosa.jpeg",
    averageRating: 4.5,
    description: "Crispy dhosa with coconut chitney",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:505,
    name: "Idli vada",
    price: 40,
    tax: 2,
    restaurantId: 5001,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\idli.jpeg",
    averageRating: 4.5,
    description: "1 bowl of noodles ",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:506,
    name: "Parota",
    price: 50,
    tax: 4,
    restaurantId: 5001,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\parota.jpeg",
    averageRating: 4.5,
    description: "Kerala  parota with curry",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:507,
    name: "Palav",
    price: 170,
    tax: 3,
    restaurantId: 5001,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\palav.jpeg",
    averageRating: 4.5,
    description: "1 bowl of Palav",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:508,
    name: "FriedRice",
    price: 100,
    tax: 3,
    restaurantId: 5001,
    category: "Lunch",
    availability: true,
    imageUrl: "assets\food\veg\friedrice.jpeg",
    averageRating: 4.5,
    description: "1 plate of rice with saas ",
    cuisine: "chinese",
    type:"Veg"
},
{
    id:509,
    name: "Mirchi Bajji",
    price: 150,
    tax: 3,
    restaurantId: 5001,
    category: "Snacks",
    availability: true,
    imageUrl: "assets\food\veg\mirchi.jpeg",
    averageRating: 4.5,
    description: " ",
    cuisine: "SouthIndian",
    type:"Veg"
    },
{
    id:510,
    name: "Uddi vada",
    price: 50,
    tax: 3,
    restaurantId: 5001,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\vada.jpeg",
    averageRating: 4.5,
    description: "2 vada with chtney",
    cuisine: "SouthIndian",
    type:"Veg"
},
{
    id: 501,
    name: "Joallad Rotti",
    price: 50,
    tax: 3,
    restaurantId: 5002,
    category: "Lunch",
    availability: true,
    imageUrl: "assets\food\veg\veg\roti.jpeg",
    averageRating: 4.5,
    description: "1 leg piece,1 tikka piece with rice",
    cuisine: "SouthIndian",
    type:"Veg",
},
{
    id:502,
    name: "Holige",
    price: 50,
    tax: 5,
    restaurantId: 5002,
    category: "Sweets",
    availability: true,
    imageUrl: "assets\food\veg\holige.jpeg",
    averageRating: 5,
    description: "Bhadam holige with ghee",
    cuisine: "southIndian",
    type:"Veg",
},
{
    id:503,
    name: "Chapati curry",
    price: 50,
    tax: 4,
    restaurantId: 5002,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg/chapati.jpeg",
    averageRating: 4.5,
    description: "Two chapati and twa types of curry",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:504,
    name: "Dhosa",
    price: 35,
    tax: 2,
    restaurantId: 5002,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\dhosa.jpeg",
    averageRating: 4.5,
    description: "Crispy dhosa with coconut chitney",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:505,
    name: "Idli vada",
    price: 40,
    tax: 2,
    restaurantId: 5002,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\idli.jpeg",
    averageRating: 4.5,
    description: "1 bowl of noodles ",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:506,
    name: "Parota",
    price: 50,
    tax: 4,
    restaurantId: 5002,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\parota.jpeg",
    averageRating: 4.5,
    description: "Kerala  parota with curry",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:507,
    name: "Palav",
    price: 170,
    tax: 3,
    restaurantId: 5002,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\palav.jpeg",
    averageRating: 4.5,
    description: "1 bowl of Palav",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:508,
    name: "FriedRice",
    price: 100,
    tax: 3,
    restaurantId: 5002,
    category: "Lunch",
    availability: true,
    imageUrl: "assets\food\veg\friedrice.jpeg",
    averageRating: 4.5,
    description: "1 plate of rice with saas ",
    cuisine: "chinese",
    type:"Veg"
},
{
    id:509,
    name: "Mirchi Bajji",
    price: 150,
    tax: 3,
    restaurantId: 5002,
    category: "Snacks",
    availability: true,
    imageUrl: "assets\food\veg\mirchi.jpeg",
    averageRating: 4.5,
    description: " ",
    cuisine: "SouthIndian",
    type:"Veg"
},
{
    id:510,
    name: "Uddi vada",
    price: 50,
    tax: 3,
    restaurantId: 5002,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\vada.jpeg",
    averageRating: 4.5,
    description: "2 vada with chtney",
    cuisine: "SouthIndian",
    type:"Veg"
},
{
    id: 501,
    name: "Joallad Rotti",
    price: 50,
    tax: 3,
    restaurantId: 5003,
    category: "Lunch",
    availability: true,
    imageUrl: "assets\food\veg\veg\roti.jpeg",
    averageRating: 4.5,
    description: "1 leg piece,1 tikka piece with rice",
    cuisine: "SouthIndian",
    type:"Veg",
},
{
    id:502,
    name: "Holige",
    price: 50,
    tax: 5,
    restaurantId: 5003,
    category: "Sweets",
    availability: true,
    imageUrl: "assets\food\veg\holige.jpeg",
    averageRating: 5,
    description: "Bhadam holige with ghee",
    cuisine: "southIndian",
    type:"Veg",
},
{
    id:503,
    name: "Chapati curry",
    price: 50,
    tax: 4,
    restaurantId: 5003,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg/chapati.jpeg",
    averageRating: 4.5,
    description: "Two chapati and twa types of curry",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:504,
    name: "Dhosa",
    price: 35,
    tax: 2,
    restaurantId: 5003,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\dhosa.jpeg",
    averageRating: 4.5,
    description: "Crispy dhosa with coconut chitney",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:505,
    name: "Idli vada",
    price: 40,
    tax: 2,
    restaurantId: 5003,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\idli.jpeg",
    averageRating: 4.5,
    description: "1 bowl of noodles ",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:506,
    name: "Parota",
    price: 50,
    tax: 4,
    restaurantId: 5003,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\parota.jpeg",
    averageRating: 4.5,
    description: "Kerala  parota with curry",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:507,
    name: "Palav",
    price: 170,
    tax: 3,
    restaurantId: 5003,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\palav.jpeg",
    averageRating: 4.5,
    description: "1 bowl of Palav",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:508,
    name: "FriedRice",
    price: 100,
    tax: 3,
    restaurantId: 5003,
    category: "Lunch",
    availability: true,
    imageUrl: "assets\food\veg\friedrice.jpeg",
    averageRating: 4.5,
    description: "1 plate of rice with saas ",
    cuisine: "chinese",
    type:"Veg"
},
{
    id:509,
    name: "Mirchi Bajji",
    price: 150,
    tax: 3,
    restaurantId: 5003,
    category: "Snacks",
    availability: true,
    imageUrl: "assets\food\veg\mirchi.jpeg",
    averageRating: 4.5,
    description: " ",
    cuisine: "SouthIndian",
    type:"Veg"
},
{
    id:510,
    name: "Uddi vada",
    price: 50,
    tax: 3,
    restaurantId: 5003,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\vada.jpeg",
    averageRating: 4.5,
    description: "2 vada with chtney",
    cuisine: "SouthIndian",
    type:"Veg"
},
{
    id: 501,
    name: "Joallad Rotti",
    price: 50,
    tax: 3,
    restaurantId: 5004,
    category: "Lunch",
    availability: true,
    imageUrl: "assets\food\veg\veg\roti.jpeg",
    averageRating: 4.5,
    description: "1 leg piece,1 tikka piece with rice",
    cuisine: "SouthIndian",
    type:"Veg",
},
{
    id:502,
    name: "Holige",
    price: 50,
    tax: 5,
    restaurantId: 5004,
    category: "Sweets",
    availability: true,
    imageUrl: "assets\food\veg\holige.jpeg",
    averageRating: 5,
    description: "Bhadam holige with ghee",
    cuisine: "southIndian",
    type:"Veg",
    },
{
    id:503,
    name: "Chapati curry",
    price: 50,
    tax: 4,
    restaurantId: 5004,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg/chapati.jpeg",
    averageRating: 4.5,
    description: "Two chapati and twa types of curry",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:504,
    name: "Dhosa",
    price: 35,
    tax: 2,
    restaurantId: 5004,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\dhosa.jpeg",
    averageRating: 4.5,
    description: "Crispy dhosa with coconut chitney",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:505,
    name: "Idli vada",
    price: 40,
    tax: 2,
    restaurantId: 5004,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\idli.jpeg",
    averageRating: 4.5,
    description: "1 bowl of noodles ",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:506,
    name: "Parota",
    price: 50,
    tax: 4,
    restaurantId: 5004,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\parota.jpeg",
    averageRating: 4.5,
    description: "Kerala  parota with curry",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:507,
    name: "Palav",
    price: 170,
    tax: 3,
    restaurantId: 5004,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\palav.jpeg",
    averageRating: 4.5,
    description: "1 bowl of Palav",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:508,
    name: "FriedRice",
    price: 100,
    tax: 3,
    restaurantId: 5004,
    category: "Lunch",
    availability: true,
    imageUrl: "assets\food\veg\friedrice.jpeg",
    averageRating: 4.5,
    description: "1 plate of rice with saas ",
    cuisine: "chinese",
    type:"Veg"
},
{
    id:509,
    name: "Mirchi Bajji",
    price: 150,
    tax: 3,
    restaurantId: 5004,
    category: "Snacks",
    availability: true,
    imageUrl: "assets\food\veg\mirchi.jpeg",
    averageRating: 4.5,
    description: " ",
    cuisine: "SouthIndian",
    type:"Veg"
},
{
    id:510,
    name: "Uddi vada",
    price: 50,
    tax: 3,
    restaurantId: 5004,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\vada.jpeg",
    averageRating: 4.5,
    description: "2 vada with chtney",
    cuisine: "SouthIndian",
    type:"Veg"
},
{
    id: 501,
    name: "Joallad Rotti",
    price: 50,
    tax: 3,
    restaurantId: 5005,
    category: "Lunch",
    availability: true,
    imageUrl: "assets\food\veg\veg\roti.jpeg",
    averageRating: 4.5,
    description: "1 leg piece,1 tikka piece with rice",
    cuisine: "SouthIndian",
    type:"Veg",
},
{
    id:502,
    name: "Holige",
    price: 50,
    tax: 5,
    restaurantId: 5005,
    category: "Sweets",
    availability: true,
    imageUrl: "assets\food\veg\holige.jpeg",
    averageRating: 5,
    description: "Bhadam holige with ghee",
    cuisine: "southIndian",
    type:"Veg",
},
{
    id:503,
    name: "Chapati curry",
    price: 50,
    tax: 4,
    restaurantId: 5005,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg/chapati.jpeg",
    averageRating: 4.5,
    description: "Two chapati and twa types of curry",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:504,
    name: "Dhosa",
    price: 35,
    tax: 2,
    restaurantId: 5005,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\dhosa.jpeg",
    averageRating: 4.5,
    description: "Crispy dhosa with coconut chitney",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:505,
    name: "Idli vada",
    price: 40,
    tax: 2,
    restaurantId: 5005,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\idli.jpeg",
    averageRating: 4.5,
    description: "1 bowl of noodles ",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:506,
    name: "Parota",
    price: 50,
    tax: 4,
    restaurantId: 5005,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\parota.jpeg",
    averageRating: 4.5,
    description: "Kerala  parota with curry",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:507,
    name: "Palav",
    price: 170,
    tax: 3,
    restaurantId: 5005,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\palav.jpeg",
    averageRating: 4.5,
    description: "1 bowl of Palav",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:508,
    name: "FriedRice",
    price: 100,
    tax: 3,
    restaurantId: 5005,
    category: "Lunch",
    availability: true,
    imageUrl: "assets\food\veg\friedrice.jpeg",
    averageRating: 4.5,
    description: "1 plate of rice with saas ",
    cuisine: "chinese",
    type:"Veg"
},
{
    id:509,
    name: "Mirchi Bajji",
    price: 150,
    tax: 3,
    restaurantId: 5005,
    category: "Snacks",
    availability: true,
    imageUrl: "assets\food\veg\mirchi.jpeg",
    averageRating: 4.5,
    description: " ",
    cuisine: "SouthIndian",
    type:"Veg"
},
{
    id:510,
    name: "Uddi vada",
    price: 50,
    tax: 3,
    restaurantId: 5005,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\vada.jpeg",
    averageRating: 4.5,
    description: "2 vada with chtney",
    cuisine: "SouthIndian",
    type:"Veg"
},
{
    id: 501,
    name: "Joallad Rotti",
    price: 50,
    tax: 3,
    restaurantId: 5006,
    category: "Lunch",
    availability: true,
    imageUrl: "assets\food\veg\veg\roti.jpeg",
    averageRating: 4.5,
    description: "1 leg piece,1 tikka piece with rice",
    cuisine: "SouthIndian",
    type:"Veg",
},
{
    id:502,
    name: "Holige",
    price: 50,
    tax: 5,
    restaurantId: 5006,
    category: "Sweets",
    availability: true,
    imageUrl: "assets\food\veg\holige.jpeg",
    averageRating: 5,
    description: "Bhadam holige with ghee",
    cuisine: "southIndian",
    type:"Veg",
},
{
    id:503,
    name: "Chapati curry",
    price: 50,
    tax: 4,
    restaurantId: 5006,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg/chapati.jpeg",
    averageRating: 4.5,
    description: "Two chapati and twa types of curry",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:504,
    name: "Dhosa",
    price: 35,
    tax: 2,
    restaurantId: 5006,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\dhosa.jpeg",
    averageRating: 4.5,
    description: "Crispy dhosa with coconut chitney",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:505,
    name: "Idli vada",
    price: 40,
    tax: 2,
    restaurantId: 5006,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\idli.jpeg",
    averageRating: 4.5,
    description: "1 bowl of noodles ",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:506,
    name: "Parota",
    price: 50,
    tax: 4,
    restaurantId: 5006,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\parota.jpeg",
    averageRating: 4.5,
    description: "Kerala  parota with curry",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:507,
    name: "Palav",
    price: 170,
    tax: 3,
    restaurantId: 5006,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\palav.jpeg",
    averageRating: 4.5,
    description: "1 bowl of Palav",
    cuisine: "southIndian",
    type:"Veg"
},
{
    id:508,
    name: "FriedRice",
    price: 100,
    tax: 3,
    restaurantId: 5006,
    category: "Lunch",
    availability: true,
    imageUrl: "assets\food\veg\friedrice.jpeg",
    averageRating: 4.5,
    description: "1 plate of rice with saas ",
    cuisine: "chinese",
    type:"Veg"
},
{
    id:509,
    name: "Mirchi Bajji",
    price: 150,
    tax: 3,
    restaurantId: 5006,
    category: "Snacks",
    availability: true,
    imageUrl: "assets\food\veg\mirchi.jpeg",
    averageRating: 4.5,
    description: " ",
    cuisine: "SouthIndian",
    type:"Veg"
},
{
    id:510,
    name: "Uddi vada",
    price: 50,
    tax: 3,
    restaurantId: 5006,
    category: "Break Fast",
    availability: true,
    imageUrl: "assets\food\veg\vada.jpeg",
    averageRating: 4.5,
    description: "2 vada with chtney",
    cuisine: "SouthIndian",
    type:"Veg"
},
]